# permissions for end users to edit filetransfers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: filetransfer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-storage-file-operator
    app.kubernetes.io/part-of: cloud-storage-file-operator
    app.kubernetes.io/managed-by: kustomize
  name: filetransfer-editor-role
rules:
- apiGroups:
  - csfo.sijoma.dev
  resources:
  - filetransfers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csfo.sijoma.dev
  resources:
  - filetransfers/status
  verbs:
  - get
