---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - csfo.sijoma.dev
  resources:
  - filetransfers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csfo.sijoma.dev
  resources:
  - filetransfers/finalizers
  verbs:
  - update
- apiGroups:
  - csfo.sijoma.dev
  resources:
  - filetransfers/status
  verbs:
  - get
  - patch
  - update
