apiVersion: csfo.sijoma.dev/v1alpha1
kind: FileTransfer
metadata:
  name: filetransfer-sample
spec:
  bucketName: "name-of-bucket"
  query:
    prefix: "your-obj-prefix"
  copyDestination:
    prefix: "our-dst-prefix"
  bucketSecret:
    name: "bucket-credentials"
    namespace: ""
